[package]
name = "aconfig_storage_file"
version = "0.1.0"
edition = "2021"

[features]
default = ["cargo"]
cargo = []

[dependencies]
anyhow = "1.0.69"
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"
