#!/usr/bin/env bash
#
# Copyright 2024, The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

echo "--- start ---"
build/soong/soong_ui.bash --make-mode build_test_suites
echo "--- end build_test_suites build ---"

cp out/soong/release-config/release_config-aosp_arm64-trunk_staging.vars $DIST_DIR/before_release_config-aosp_arm64-trunk_staging.vars

$(build/soong/soong_ui.bash --dumpvar-mode HOST_OUT)/bin/build_test_suites $@

cp out/soong/release-config/release_config-aosp_arm64-trunk_staging.vars $DIST_DIR/after_release_config-aosp_arm64-trunk_staging.vars