[workspace]

members = [
    "aconfig",
    "aconfig_protos",
    "aconfig_storage_file",
    "aconfig_storage_read_api",
    "aconfig_storage_write_api",
    "aflags", "load_aconfig_proto_paths",
    "printflags"
]

resolver = "2"
